on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: extract package version
        id: semver_package
        uses: Saionaro/extract-package-version@v1.0.6
      - name: extract semantic version
        id: semver 
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.semver_package.outputs.version }}
      - name: extract npm tag
        id: npmpublish
        run: |
          echo "${PRERELEASE}" | sed 's/[0-9]*\.[0-9]*\.[0-9]*\-\([^.+]*\).*/::set-output name=tag::\1/'
        env: 
          PRERELEASE: ${{steps.semver.outputs.fullversion}}           
      - name: extracted version
        run: |
          echo "## npm"
          echo "version: ${{ steps.semver_package.outputs.version }}"
          echo "tag: ${{ steps.npmpublish.outputs.tag }}"
          echo ""
          echo "## tag"
          echo "version: ${{ steps.semver.outputs.fullversion }}"
          echo "major: ${{ steps.semver.outputs.major }}"
          echo "minor: ${{ steps.semver.outputs.minor }}"
          echo "patch: ${{ steps.semver.outputs.patch }}"
          echo "prerelease: ${{ steps.semver.outputs.prerelease }}"
          echo "build: ${{ steps.semver.outputs.build }}"
      - name: build project
        run: |
          npm ci
          npm run build
        env:
            CI: true
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            NPM_TFSO_TOKEN: ${{secrets.NPM_TFSO_TOKEN}}
      - name: run tests
        run: |
          npm run lint
          npm test
        env:
            CI: true
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            NPM_TFSO_TOKEN: ${{secrets.NPM_TFSO_TOKEN}}
